version: '3'
services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_USER="${POSTGRES_USER}"
            - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
            - POSTGRES_DB="postgres"
        volumes:
            - pgdata:/var/lib/postgresql/data
        network_mode: host
volumes:
    pgdata: {}
